PMS.Web/Controllers/PISController.cs
using AutoMapper;
using PMS.ApplicationService.DTOs;
using PMS.ApplicationService.ServiceContract;
using PMS.Common.Logger;
using PMS.Web.ActionFilters;
using PMS.Web.ViewModels;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

namespace PMS.Web.Controllers
{
    public class PISController : Controller
    {
        //This is for testing only
        private readonly IPISService _pisService;
        private readonly IPISIncrementNoService _pisIncrementNoService;
        private readonly IMapper _mapper;

        public PISController(IPISService pisService, IMapper mapper, IPISIncrementNoService pisIncrementNoService)
        {
            if (pisService == null) throw new ArgumentNullException("PISService");
            if (pisIncrementNoService == null) throw new ArgumentNullException("IPISIncrementNoService");
            if (mapper == null) throw new ArgumentNullException("Mapper");
            _pisService = pisService;
            _pisIncrementNoService = pisIncrementNoService;
            _mapper = mapper;
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Recommendation(Guid PkId)
        {
            try
            {
                if (!string.IsNullOrEmpty(PkId.ToString()))
                {
                    var pisInformation = _mapper.Map<PISDto, PISInformation>(_pisService.getPISDetails(PkId, 0));
                    return View(pisInformation);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

<<<<<<< HEAD
=======

>>>>>>> e0c77c851bfb9fa3f68ef227cf7bc87ed6aca07c
        public ActionResult Edit(Guid PkId)
        {
            try
            {
                if (!string.IsNullOrEmpty(PkId.ToString()))
                {
                    var pisInformation = _mapper.Map<PISDto, PISInformation>(_pisService.getPISDetails(PkId,0));
                    return View(pisInformation);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

        public ActionResult List()
        {
            var pisList = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.GetAll());

            bool isEmpty = !pisList.Any();
            if (isEmpty)
            {
                ViewBag.countLst = "0";
                return View(pisList);

            }
            else
            {
                return View(pisList);
            }

            return View();

        }

        public ActionResult Details(Guid PkId)
        {
            try
            {
                if (!string.IsNullOrEmpty(PkId.ToString()))
                {
                    var pisInformation = _mapper.Map<PISDto, PISInformation>(_pisService.getPISDetails(PkId,0));
                    return View(pisInformation);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult CreatePIS(PISInformation pi, string btnDraft, string btnSubmit)
        {
            try
            {

                bool bDraft = false;
                bool bSubmit = false;
                string message = "";
                if (btnDraft != null)
                {
                    bDraft = true;
                    message = "Record has been successfully saved as draft";
                }
                if (btnSubmit != null)
                {
                    bSubmit = true;
                    message = "Record has been successfully submitted";
                }

               // if (ModelState.IsValid)
                //{
                    var pisNo = _mapper.Map<PISIncrementNoDto, PISIncrementNoModel>(_pisIncrementNoService.GetPISNo());
                    DateTime now = DateTime.Now;
                    PISDto newPIS = new PISDto
                    {

                        PkId = Guid.NewGuid(),
                        Name = pi.Name,
                        PISNo = now.Year.ToString() + "-" + pisNo.PISNodisplay,
                        Position = pi.Position,
                        DepartmentBU = pi.DepartmentBU,
                        Manager = pi.Manager,
                        BusinessObjective = pi.BusinessObjective,
                        Request = pi.Request,
                        IsDraft = bDraft,
                        IsSubmit = bSubmit,
                        DateCreated = DateTime.Now,
                        RequestStatus = "N",
                    };
                    _pisService.CreatePIS(newPIS);
                    _pisIncrementNoService.UpdatePISNo();
                    TempData["alertMessage"] = message; 
                    return RedirectToAction("Details", new { PkId = newPIS.PkId });
                //}
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View(pi);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult UpdatePIS(PISInformation pi, string btnDraft, string btnSubmit)
        {
            try
            {

                bool bDraft = false;
                bool bSubmit = false;
                string message = "";
                if (btnDraft != null)
                {
                    bDraft = true;
                    message = "Record has been successfully saved as draft";
                }
                if (btnSubmit != null)
                {
                    bSubmit = true;
                    message = "Record has been successfully submitted";
                }

                //if (ModelState.IsValid)
                //{
                    PISDto newPIS = new PISDto
                    {
                        Id = pi.Id,
                        PkId = pi.PkId,
                        Name = pi.Name,
                        Position = pi.Position,
                        DepartmentBU = pi.DepartmentBU,
                        Manager = pi.Manager,
                        BusinessObjective = pi.BusinessObjective,
                        Request = pi.Request,
                        IsDraft = bDraft,
                        IsSubmit = bSubmit,
                        PISNo = pi.PISNo

                    };
                    _pisService.UpdatePIS(newPIS);
                    TempData["alertMessage"] = message;
                    return RedirectToAction("Details", new { PkId = newPIS.PkId });
                //}
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View(pi);
        }

        public ActionResult Delete(int id)
        {
            try
            {
                //Thread.Sleep(3000);
                _pisService.DeletePIS(id);
                TempData["alertMessage"] = "Record has been successfully deleted";
                //return this.Json(id, JsonRequestBehavior.AllowGet);
                string url = Request.UrlReferrer.ToString();
                return Json(new { redirectToUrl = url }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return View("List");
                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            // return RedirectToAction("List");
        }

        public ActionResult FlagSubmitPIS(int Id)
        {
            try
            {

                _pisService.UpdateIsSubmit(Id);
               // var pisInfo = _pisService.getPISDetails(new Guid(),Id);
                TempData["alertMessage"] = "Record has been successfully submitted";
                return Redirect(Request.UrlReferrer.ToString());
            }
            catch (Exception ex)
            {
                return View("List");
                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            // return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult SaveRecommendation(PISInformation pi)
        {
            try
            {

                PISDto newPIS = new PISDto
                {
                    Id = pi.Id,
                    PkId = pi.PkId,
                    AppType = pi.AppType,
                    ProjectWeight = pi.ProjectWeight,
                    AppDevTeam = pi.AppDevTeam,
                    AppManager = pi.AppManager,
                    AppDev = pi.AppDev,
                    SolutionRecommendation = pi.SolutionRecommendation,
                };
                _pisService.UpdatePISRecommendation(newPIS);

                TempData["alertMessage"] = "Additional details has been added";
                return Redirect(Request.UrlReferrer.ToString());
                //return RedirectToAction("Details", new { PkId = newPIS.PkId, role = "admin" });

<<<<<<< HEAD
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult SendAcknowledgement(PISInformation pi)
        {
            try
            {
                PISDto newPIS = new PISDto
                {
                    Id = pi.Id,
                    CabReviewSchedule = pi.CabReviewSchedule,
                    CabNote = pi.CabNote,
                    RequestStatus = "C",

                };
                _pisService.UpdateCabSchedule(newPIS);

PMS.Web/Views/PIS/Create.cshtml
@model PMS.Web.ViewModels.PISInformation
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<small class="form-text text-muted">
    <a href="@Url.Action("List", "PIS")" class="nounderline text-muted"><< Back to list</a>
</small><br>
<div>

    @using (Html.BeginForm("CreatePIS", "PIS", FormMethod.Post))
    {
        <h6 class="float-left">Project Information</h6>
        <br><br>
        <hr />



        <div class="card-header">
            <h6>Requestor Details</h6>
        </div><br>


        <div class="row">
            <div class="form-group col-md-6">
                <label>Name</label>
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control input-sm", maxlength = 150 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })</small>

            </div>

            <div class="form-group col-md-6">
                <label>Position</label>
                @Html.TextBoxFor(model => model.Position, new { @class = "form-control", maxlength = 150 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })</small>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label>Department / BU</label>
                @Html.TextBoxFor(model => model.DepartmentBU, new { @class = "form-control", maxlength = 150 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.DepartmentBU, "", new { @class = "text-danger" })</small>
            </div>

            <div class="form-group col-md-6">
                <label>BU/CCU IS Manager</label>
                @Html.TextBoxFor(model => model.Manager, new { @class = "form-control", maxlength = 150 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })</small>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label>Business Objectives</label>
                @Html.TextAreaFor(model => model.BusinessObjective, new { @class = "form-control", rows = "5", maxlength = 4000 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.BusinessObjective, "", new { @class = "text-danger" })</small>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label>Request</label>
                @Html.TextAreaFor(model => model.Request, new { @class = "form-control", rows = "5", maxlength = 4000 })
                <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.Request, "", new { @class = "text-danger" })</small>
            </div>
        </div>
        <br><br>

        <button type="submit" name="btnDraft" value="Draft" class="btn btn-sm btn-success"><i class="fas fas fa fa-save">&nbsp;</i>Save as Draft</button>

        <button type="submit" name="btnSubmit" value="Submit" class="btn btn-sm btn-primary"><i class="fas fas fa fa-check-circle">&nbsp;</i>Submit PIS</button>
        <br><br>
    }

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/PMS/pis.js")"></script>
}

PMS.Web/Views/PIS/Edit.cshtml
@model PMS.Web.ViewModels.PISInformation
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<small class="form-text text-muted ">
    <a href="@Url.Action("List", "PIS")" class="nounderline btl"><< Back to list</a>
</small><br>
        <div>
            @using (Html.BeginForm("UpdatePIS", "PIS", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.PISNo, new { @class = "form-control d-none" })
                @Html.TextBoxFor(model => model.PkId, new { @class = "form-control d-none" })
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control d-none" })
                <h6 class="float-left">Edit Project Information</h6>
                <br><br>
                <hr />



                <div class="card-header">
                    <h6>Requestor Details</h6>
                </div><br>

                //, @readonly = true
                <div class="row">
                    <div class="form-group col-md-6">
                        <label>Name</label>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", maxlength = 150 })
                        <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })</small>

                    </div>

                    <div class="form-group col-md-6">
                        <label>Position</label>
                        @Html.TextBoxFor(model => model.Position, new { @class = "form-control", maxlength = 150 })
                        @*<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label>Department / BU</label>
                        @Html.TextBoxFor(model => model.DepartmentBU, new { @class = "form-control", maxlength = 150 })
                        @*<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
                    </div>

                    <div class="form-group col-md-6">
                        <label>BU/CCU IS Manager</label>
                        @Html.TextBoxFor(model => model.Manager, new { @class = "form-control", maxlength = 150 })
                        @*<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label>Business Objectives</label>
                        @Html.TextAreaFor(model => model.BusinessObjective, new { @class = "form-control", rows = "5", maxlength = 4000 })

                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label>Request</label>
                        @Html.TextAreaFor(model => model.Request, new { @class = "form-control", rows = "5", maxlength = 4000 })

                    </div>
                </div>
                <br><br>

                

                <button type="submit" name="btnDraft" value="Draft" class="btn btn-sm btn-success"><i class="fas fas fa fa-save">&nbsp;</i>Save as Draft</button>

                <button type="submit" name="btnSubmit" value="Submit" class="btn btn-sm btn-primary"><i class="fas fas fa fa-check-circle">&nbsp;</i>Submit PIS</button>

                <br><br>
            }

        </div>

PMS.Web/Views/PIS/List.cshtml
@model IEnumerable<PMS.Web.ViewModels.PISInformation>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div>
        <h6 class="float-left">My Ticket List</h6>
    </div>

    <div class="float-right">
        <a href="@Url.Action("Create", "PIS")" class="btn btn-sm btn-primary"><i class="fas fas fa fa-plus-square">&nbsp;</i>Create PIS</a>
    </div>
    <br />
    <br />
    <hr />
    <div class="card mb-3">
        <div class="card-header">
            <input class="form-control py-2 border-right-0 border d-none" placeholder="Search..." type="search" id="example-search-input">
        </div>
        <div class="card-body">
            <table class="table" id="dataTable">
                <thead>
                    <tr>
                        <th>PIS Number </th>
                        <th>Title</th>
                        <th>Application</th>
                        <th>Type</th>
                        <th>Requestor</th>
                        <th>Date Submitted</th>
                        <th>CAB Review Schedule</th>
                        <th>Status</th>
                        <th width="10%" align="center" style="text-align:center;">Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>

                                @Html.DisplayFor(modelItem => item.PISNo)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.AppName)

<<<<<<< HEAD
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AppType)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)

                        </td>
                        <td>
                            @String.Format("{0: MM/d/yyyy}", item.DateCreated)
                            @*@Html.DisplayFor(modelItem => item.DateCreated)*@

                        </td>
                        <td>
                            @String.Format("{0: MM/d/yyyy}", item.CabReviewSchedule)
                            @*@Html.DisplayFor(modelItem => item.CabReviewSchedule)*@

                        </td>
                        <td>
                            @if (item.IsSubmit == true && item.CabReviewSchedule != null && item.IsApprovedPIS == true && item.IsApproved == true)
                            {
                                <p class="text text-danger">Approved BRS</p>
                            }
                            else if (item.IsSubmit == true && item.CabReviewSchedule != null && item.IsApprovedPIS == true)
                            {
                                <p class="text text-danger">Approved PIS</p>
                            }

                            else if (item.IsSubmit == true && item.CabReviewSchedule != null)
                            {
                                <p class="text text-danger">For CAB Review</p>
                            }
                            else if (item.IsSendBack == true && item.IsSubmit == true)
                            {
                                <p class="text text-danger">Rejected</p>
                            }
                            else if (item.IsSubmit == true && item.IsDraft != true)
                            {
                                <p class="text text-danger">For Approval</p>
                            }
                            else if (item.IsDraft == true)
                            {
                                <p class="text text-danger">New</p>
                            }
                            else
                            {
                                <p class="text text-danger">No Status</p>
                            }
                        </td>
=======
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DateCreated)

                            </td>

                            <td>
                                @if (item.IsDraft == true)
                                {
                                    <p class="text text-danger">New</p>
                                }
                                else if (item.IsSubmit == true)
                                {
                                    <p class="text text-danger">For Approval</p>
                                }
                                else
                                {
                                    <p class="text text-danger">No Status</p>
                                }


                            </td>
>>>>>>> e0c77c851bfb9fa3f68ef227cf7bc87ed6aca07c

                            <td align="center">

<<<<<<< HEAD
                            @*@Html.ActionLink("Edit", "Edit", new { recordId = item.RecordId, }) | data-id="@item.RecordId"
            @Html.ActionLink("Details", "Details", new { recordId = item.RecordId })
            @Html.ActionLink("Delete", "Delete", new { recordId = item.RecordId })*@
                            @if (item.IsDraft == true)
                            {
                                <a href="@Url.Action("Edit", "PIS", new {PkId=item.PkId.ToString()})" class="anchorDetail" data-name="edit" data-toggle="tooltip" title="Edit"><i class="fa fa-edit text text-muted"></i></a>
=======
                                @*@Html.ActionLink("Edit", "Edit", new { recordId = item.RecordId, }) | data-id="@item.RecordId"
                                    @Html.ActionLink("Details", "Details", new { recordId = item.RecordId })
                                    @Html.ActionLink("Delete", "Delete", new { recordId = item.RecordId })*@
                                @if (item.IsDraft == true)
                                {
                                    <a href="@Url.Action("Edit", "PIS", new {PkId=item.PkId.ToString()})" class="anchorDetail" data-name="edit" data-toggle="tooltip" title="Edit"><i class="fa fa-edit text text-muted"></i></a>
>>>>>>> e0c77c851bfb9fa3f68ef227cf7bc87ed6aca07c

                                }

<<<<<<< HEAD
                            &nbsp;|
                            <a href="@Url.Action("Details", "PIS", new {PkId=item.PkId.ToString(),BRSId=item.BRSId})" class="anchorDetail" data-name="detail" data-toggle="tooltip" title="View Details"><i class="fa fa-eye text text-muted"></i></a>&nbsp;|
=======
                                &nbsp;|
                                <a href="@Url.Action("Details", "PIS", new {PkId=item.PkId.ToString()})" class="anchorDetail" data-name="detail" data-toggle="tooltip" title="View Details"><i class="fa fa-eye text text-muted"></i></a>&nbsp;|
>>>>>>> e0c77c851bfb9fa3f68ef227cf7bc87ed6aca07c

                                <a href="javascript:void(0);" class="anchorConfirm" data-id="@item.Id" data-name="delete" data-action="/PIS/Delete"><i class="fa fa-trash text text-danger" data-toggle="tooltip" title="Delete "></i></a>

                            </td>
                        </tr>
                    }
                    @if (ViewBag.countLst == "0")
                    {
                        <tr>
                            <td colspan="10" align="center">
                                <strong class="text text-default">No data found.</strong>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="card-footer small text-muted">Date/TIme:@DateTime.Now</div>


    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/PMS/app/confirm-pis.js")"></script>
}

PMS.Web/Views/PIS/Recommendation.cshtml
@model PMS.Web.ViewModels.PISInformation
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string sRole = Request.QueryString["role"];
}

<small class="form-text text-muted ">
    <a href="@Url.Action("Details", "PIS",new { Pkid = Model.PkId,role =sRole})" class="nounderline btl"><< Back to details</a>
</small><br>
<div>
    @using (Html.BeginForm("SaveRecommendation", "PIS", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.PISNo, new { @class = "form-control d-none" })
        @Html.TextBoxFor(model => model.PkId, new { @class = "form-control d-none" })
        @Html.TextBoxFor(model => model.Id, new { @class = "form-control d-none" })

        <h6 class="float-left">Recommendation</h6>
        <div class="pull-right">
            <div class="row pull-right">
                <label>PIS Number :</label>       @Html.DisplayFor(model => model.PISNo)
                &nbsp;&nbsp;&nbsp;
                @*<label>BRS Number :</label>2019-0000000001*@
            </div>
        </div>
        <br><br>
        <hr />
        <br />
        <div class="form-group col-md-6">
            <label>Project type</label>
            @Html.DropDownListFor(m => m.AppType, new List<SelectListItem>
         {
                             new SelectListItem() {Text = "Please select", Value=""},
                             new SelectListItem() {Text = "Project", Value="Project"},
                             new SelectListItem() {Text = "Not a Project", Value="Not a Project"}
         }, new { @class = "form-control", @required="required" })


        </div>

        <div class="form-group col-md-6">
            <label>Project Weight</label>
            @Html.DropDownListFor(m => m.ProjectWeight, new List<SelectListItem>
     {
                         new SelectListItem() {Text = "Please select", Value=""},
                         new SelectListItem() {Text = "Small-Minor", Value="Small-Minor"},
                         new SelectListItem() {Text = "Small-Major", Value="Small-Major"},
                           new SelectListItem() {Text = "Big-Minor", Value="Big-Minor"},
                         new SelectListItem() {Text = "Big-Major", Value="Big-Major"}
     }, new { @class = "form-control" , @required = "required" })
            <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.ProjectWeight, "", new { @class = "text-danger" })</small>
        </div>

        <div class="form-group col-md-6">
            <label>App-Dev Team</label>
            @Html.DropDownListFor(m => m.AppDevTeam, new List<SelectListItem>
    {
                  new SelectListItem() {Text = "Please select", Value=""},
                  new SelectListItem() {Text = "Web", Value="Web"},
                  new SelectListItem() {Text = "Mobile", Value="Mobile"},
    }, new { @class = "form-control", @required = "required" })
            <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.AppDevTeam, "", new { @class = "text-danger" })</small>
        </div>

        <div class="form-group col-md-6">
            <label>Application Manager</label>
            @Html.DropDownListFor(m => m.AppManager, new List<SelectListItem>
    {
                  new SelectListItem() {Text = "Please select", Value=""},
                  new SelectListItem() {Text = "Paul Villalobos", Value="Paul Villalobos"},
                  new SelectListItem() {Text = "Juan Dela Cruz", Value="Juan Dela Cruz"}
    }, new { @class = "form-control", @required = "required" })
            <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.AppManager, "", new { @class = "text-danger" })</small>
        </div>

        <div class="form-group col-md-6">
            <label>Application Developer</label>
            @Html.DropDownListFor(m => m.AppDev, new List<SelectListItem>
    {
             new SelectListItem() {Text = "Please select", Value=""},
             new SelectListItem() {Text = "Paul Villalobos", Value="Paul Villalobos"},
             new SelectListItem() {Text = "Juan Dela Cruz", Value="Juan Dela Cruz"}
    }, new { @class = "form-control", @required = "required" })
            <small class="form-text text-danger">@Html.ValidationMessageFor(model => model.AppDev, "", new { @class = "text-danger" })</small>
        </div>

        <div class="form-group col-md-12">
            <label>SolutionRecommendation</label>
            @Html.TextAreaFor(model => model.SolutionRecommendation, new { @class = "form-control", rows = "5", maxlength = 4000, @required = "required" })
         
        </div>


        <button type="submit" class="btn btn-sm btn-primary">Update</button>
        <br><br>

        @*<div class="card-header">
                <h6>Solution Recommendation</h6>
            </div><br>*@
    }

</div>