PMS.Web/Controllers/MainController.cs
using AutoMapper;
using PMS.ApplicationService.DTOs;
using PMS.ApplicationService.ServiceContract;
using PMS.Common.Logger;
using PMS.Web.ActionFilters;
using PMS.Web.ViewModels;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

namespace PMS.Web.Controllers
{
    public class MainController : Controller
    {
        private readonly IPISService _pisService;
        private readonly IBRSService _brsService;
        private readonly IMapper _mapper;

        public MainController(IPISService pisService, IMapper mapper, IBRSService brsService)
        {
            if (pisService == null) throw new ArgumentNullException("PISService");
            if (brsService == null) throw new ArgumentNullException("BRSService");
            if (mapper == null) throw new ArgumentNullException("Mapper");
            _pisService = pisService;
            _brsService = brsService;
            _mapper = mapper;
        }

        public ActionResult Dashboard()
        {

            var countNew = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("new"));
            ViewBag.countNew = countNew.Count();

            var countCab = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("cab"));
            ViewBag.countCab = countCab.Count();

            var countPis = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("pis"));
            ViewBag.countPis = countPis.Count();

            var countAlladmin = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("all"));
            ViewBag.countAlladmin = countAlladmin.Count();

            var countAlluser = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.GetAll());
            ViewBag.countAlluser = countAlluser.Count();

            var countBRS = _mapper.Map<IEnumerable<BRSDto>, IEnumerable<BRSModel>>(_brsService.GetAll());
            ViewBag.countBRS = countBRS.Count();


            // A array of authors  
            string[] divColor = { "warning", "success", "danger", "info", "primary"};
            // Create a Random object  
            Random rand = new Random();
            // Generate a random index less than the size of the array.  
            int index = rand.Next(divColor.Length);
            // Display the result.  
            string divPickColor = divColor[index].ToString();
            ViewBag.divPickColor = divPickColor;
            return View();
        }

    }
}

PMS.Web/Views/Shared/ErrorPage.cshtml
@{
    ViewBag.Title = "ISD Core Error Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ISD Core Error Page</h2>

<h1>application has encountered a problem</h1>

<p>
    The operation you requested has been terminated by the system.
</p>
<p>
    <b>Please let the system support team aware of this problem.</b><br />
    Contact us @@ ALLISDAppDevGroup@retaildomain.com.ph Thank you!
</p>
<p>
    A detailed error trace has been created by the system to help the support discover
                    the root cause.
</p>
<p>
    To see what error trace contains, <span class="errorTrace"><a class="btn" id="showError" onclick="ShowErrorTrace()" href="javascript:;">click here</a></span>.
</p>

<div id="errorTrace" style="display: none;">@Html.Raw(TempData["ErrorResult.Exception"])</div>

PMS.Web/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "RRHI-PMS";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="~/Content/images/favicon-small.ico" type="image/x-icon" />
    <link href="~/Content/themes/vendor/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/themes/vendor/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/themes/vendor/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/themes/vendor/css/sb-admin.css" rel="stylesheet" />
    <link href="~/Content/themes/vendor/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />






    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        #loading {
            display: none;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background: rgba(255,255,255,0.8);
            z-index: 1000;
        }

        #loadingcontent {
            display: table;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
        }

        #loadingspinner {
            display: table-cell;
            vertical-align: middle;
            width: 100%;
            text-align: center;
            font-size: larger;
            padding-top: 80px;
        }
    </style>
</head>

<body id="page-top">
    <div id="loading">
        <div id="loadingcontent">
            <p id="loadingspinner" style="font-size: 16px; font-weight: bold;">
                <i class="fas fa-circle-notch fa-spin" style="color: red; font-size: 24px;"></i>
                Please wait...
            </p>
        </div>
    </div>
    @RenderPage("~/Views/Shared/_Navigation.cshtml")
    <div id="wrapper" class="wow wow fadeIn">
        @*@RenderPage("~/Views/Shared/_SideMenu.cshtml")*@
        <div id="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>

            <footer class="sticky-footer">
                    <hr /><br /><br />

                    <div class=""> @*container*@
                        @*<div class="copyright text-right my-auto">*@
                            <div class="copyright wow fadeIn" data-wow-duration='2500ms' data-wow-delay='1000ms' >
                                <div>
                                    <small class="text  text-light ">
                                        &reg; 2019 Project Monitoring System -
                                        All Rights Reserved&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    </small>
                                    <div id="content"></div>
                                </div>
                            </div>
                        </div>
                </footer>
        </div>
    </div>


    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Modal -->
    <button type="button" class="btn btn-info btn-lg confirmModal d-none" data-toggle="modal" data-target="#confirmModal"></button>
    <div class="modal fade" id="confirmModal" role="dialog">
        <div class="modal-dialog modal-lg" style="width:50%;">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title pull-left">System Message</h6>
                </div>
                <div class="modal-body" style="font-size: 18px;text-align:center;">
                    <span>Are you sure you want to <span class="nameConfirmAction"></span>?</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary btn-sm btnConfirmOk" style="width:70px;">OK</button>
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal" style="width:70px;">Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <div id="alertMessage" style="display:none;">
        @Html.Raw(TempData["alertMessage"])
    </div>

    <div id="errorMessage" style="display:none;">
        @Html.Raw(TempData["errorMessage"])
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/PMS/")
    @RenderSection("scripts", required: false)
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/themes/vendor/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/themes/vendor/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/themes/vendor/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/themes/vendor/vendor/datatables/dataTables.bootstrap4.js"></script>
    <script src="~/Content/themes/vendor/js/sb-admin.js"></script>
    @*<script src="~/Scripts/PMS/confirm.js"></script>*@
    <script src="~/Scripts/PMS/PageLoader.js"></script>
    <script src="~/Scripts/wow.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    @*<script src="~/Scripts/PMS/app/product.js"></script>*@
    <link href="~/Content/animate.min.css" rel="stylesheet" />




    @*JS for datatable*@
    <script src="~/content/themes/vendor/js/demo/datatables-demo.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>*@
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>*@



    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();


          if ('@TempData["alertMessage"]' != "") {
              showMessage();
            '@TempData["alertMessage"] = ""';
            }

           if ('@TempData["errorMessage"]' != "") {
               errorMessage();
            '@TempData["errorMessage"] = ""';
        }

        });

        function showMessage() {
            $('#alertMessage').fadeIn("slow");
            setTimeout(function () { $("#alertMessage").fadeOut(3000); }, 4000)
             '@TempData["alertMessage"] = ""';
        }

        function errorMessage() {
            $('#errorMessage').fadeIn("slow");
            setTimeout(function () { $("#errorMessage").fadeOut(3000); }, 4000)
              '@TempData["errorMessage"] = ""';
        }



        @*$(function () {
            $("#content").html("<i class='fas fa-circle-notch fa-spin' style='color: red; font-size: 24px;'></i>");
            setTimeout(function () { LoadPartialView(); }, 500);
        });

        function LoadPartialView() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetPartialView", "Product")',
                dataType: "html",
                success: function (data) {
                    $("#content").empty();
                    $("#content").html(data);
                    $("#content").fadeIn('slow');
                },
                error: function (data) {
                    $("#content").empty();
                }
            });
        };

        $(window).on('popstate', function () {
            $(".modal-backdrop").remove();
        });*@


    </script>


</body>
</html>

PMS.Web/Views/Shared/_Navigation.cshtml
@{ 
    string togglechk = "";
    //if (!string.IsNullOrEmpty(Session["toggleCheck"] as string))
    //{
    //    Session["toggleCheck"] = "0";
    //    togglechk = Session["toggleCheck"].ToString();
    //}
    //else
    //{
    //    togglechk = "1";
    //}


    //if (!string.IsNullOrEmpty(Request.Cookies["username"].Value as string))
    //{
    //    var valuesss = Request.Cookies["username"].Value;
    //}
    //else
    //{
    //    togglechk = "1";
    //}

}


<body id="page-top" >

    <nav class="navbar navbar-expand navbar-dark bg-red static-top">

        <a class="navbar-brand mr-1" href="@Url.Action("Dashboard", "Main")">
            <img class="img  wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='100ms' src="~/Content/images/rrhi_logo.png" style="width:8%;height:8%" />
            <b>Dashboard</b>
        </a>

        @*<button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle">
            <i class="fas fa-bars"></i>
        </button>*@

        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                @*<input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-default" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>*@
            </div>
        </form>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">



            @*<li class="nav-item dropdown no-arrow mx-1 divNavP">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">9+</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>*@


            @*<li class="nav-item dropdown no-arrow mx-1 divNavP">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span class="badge badge-danger">7</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>*@



            <li class="nav-item dropdown no-arrow divNavP">
                <a class="nav-link" href="#" title="Logout" data-toggle="tooltip">
                    <i class="fas fa-sign-out-alt fa-fw"></i>
                </a>
                @*<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>*@
            </li>


        </ul>

    </nav>


</body>

PMS.Web/Views/Shared/_PartialFooter.cshtml
<span class="wow fadeIn"><img src="~/Content/images/r-icon.png" /></span>
@*@ViewBag.Test*@

PMS.Web/Views/Shared/_SideMenu.cshtml
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action("Dashboard", "Main")">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span> Dashboard</span>
        </a>
    </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="javascript:;">Login</a>
            <a class="dropdown-item" href="javascript:;">Register</a>
            <a class="dropdown-item" href="javascript:;">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="javascript:;">404 Page</a>
            <a class="dropdown-item" href="javascript:;">Blank Page</a>
        </div>
    </li>


    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Index", "Employee")">
            <i class="fas fa-fw fa-users"></i>
            <span> Employee</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("ProductList", "Product")">
            <i class="fas fa-fw fa-luggage-cart"></i>
            <span> Product</span>
        </a>
    </li>

</ul>