PMS.Web/Controllers/BRSController.cs
using AutoMapper;

using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using System.IO;
using System.Web.Security;
using System.Configuration;

using PMS.ApplicationService.DTOs;
using PMS.ApplicationService.ServiceContract;
using PMS.Common.Logger;
using PMS.Web.ActionFilters;
using PMS.Web.ViewModels;

namespace PMS.Web.Controllers
{
    public class BRSController : Controller
    {
        private readonly IBRSService _brsService;
        private readonly IPISService _pISService;
        private readonly IBRSIncrementNoService _bRSIncrementNoService;
        private readonly IMapper _mapper;

        public BRSController(IBRSService brsService, IMapper mapper, IBRSIncrementNoService bRSIncrementNoService, IPISService pISService)
        {
            if (brsService == null) throw new ArgumentNullException("BRSService");
            if (bRSIncrementNoService == null) throw new ArgumentNullException("BRSIncrementNoService");
            if (pISService == null) throw new ArgumentNullException("PISService");
            if (mapper == null) throw new ArgumentNullException("Mapper");
            _brsService = brsService;
            _bRSIncrementNoService = bRSIncrementNoService;
            _pISService = pISService;
            _mapper = mapper;
        }
        //
        // GET: /BRS/

        public ActionResult Create()
        {
            //var pisInformation = _mapper.Map<BRSIncrementNoDto, BRSIncrementNoModel>(_bRSIncrementNoService.GetBRSNo());
            return View();
        }

        public ActionResult Edit(int id)
        {
            try
            {
                if (id != null)
                {
                    var pisInformation = _mapper.Map<BRSDto, BRSModel>(_brsService.getBRSDetails(id));
                    return View(pisInformation);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var pisList = _mapper.Map<IEnumerable<BRSDto>, IEnumerable<BRSModel>>(_brsService.GetAll());

            bool isEmpty = !pisList.Any();
            if (isEmpty)
            {
                ViewBag.countLst = "0";
                return View(pisList);
            }
            else
            {
                return View(pisList);
            }

            return View();

        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            try
            {
                if (id != null)
                {
                    var pisInformation = _mapper.Map<BRSDto, BRSModel>(_brsService.getBRSDetails(id));
                    return View(pisInformation);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

        [HttpGet]
        public ActionResult GetPisNo(string pisNo)
        {
            try
            {
                if (pisNo != null)
                {
                    var pisInformation = _mapper.Map<BRSDto, BRSModel>(_brsService.GetPISNo(pisNo));
                    return Json(pisInformation, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
            return View();
        }

        [HttpPost]
        public void CreateBRS(BRSModel br)
        {
            try
            {
                var pisInformation = _mapper.Map<BRSIncrementNoDto, BRSIncrementNoModel>(_bRSIncrementNoService.GetBRSNo());

                BRSDto newBRS = new BRSDto
                {
                    PISNo = br.PISNo,
                    BRSNo = pisInformation.BRSNodisplay + "-" +  DateTime.Now.Year,
                    Notes = br.Notes,
                    BU = br.BU,
                    BRSApprovedDate = br.BRSApprovedDate,
                    FilePath = br.FilePath,
                    Filename = br.Filename,
                    Status = br.Status,
                    CreatedBy = br.CreatedBy,
                    DateCreated = DateTime.Now
                };
                _brsService.CreateBRS(newBRS);

                _bRSIncrementNoService.UpdateBRSNo();

                PISDto newPIS = new PISDto
                {
                    PISNo = br.PISNo,
                };
                _pISService.UpdateIsBRS(newPIS);

                //var q = _brsService.GetPISNo(br.PISNo);

                //string url = "Details?Id=" + q.Id;
                //return new JsonResult() { Data = new { redirectToUrl = url } };
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public void UploadCustRedeemedPDF(string pISBo)
        {
            try
            {
                var pdfFileTemp = pISBo;

                foreach (string file in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                    string extension = Path.GetExtension(hpf.FileName);
                    string BaseDir = string.Concat(ConfigurationManager.AppSettings["FileServerBaseDir"], "FILE\\");
                    string uploadFile = BaseDir + pdfFileTemp + "-" + hpf.FileName + ".pdf";

                    byte[] bytes;
                    using (BinaryReader br = new BinaryReader(hpf.InputStream))
                    {
                        bytes = br.ReadBytes(hpf.ContentLength);
                    }

                    BRSDto upBRS = new BRSDto
                    {
                        PISNo = pISBo,
                        FilePath = uploadFile,
                        Filename = pdfFileTemp + "-" + hpf.FileName,
                    };
                    _brsService.UpdatePISNo(upBRS);

                    //Create Folder if not exist
                    if (!Directory.Exists(BaseDir))
                    {
                        Directory.CreateDirectory(BaseDir);
                    }

                    if (System.IO.File.Exists(uploadFile))
                    {
                        System.IO.File.Delete(uploadFile);
                        hpf.SaveAs(uploadFile);
                    }
                    else
                    {
                        hpf.SaveAs(uploadFile);
                    }
                }
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public ActionResult DownloadBRSTemplate()
        {
            try
            {

                string filename = "2019-0000000024-BRS_PROJECT MONITORING SYSTEM.pdf" + ".pdf";
                string BaseDir = string.Concat(ConfigurationManager.AppSettings["FileServerBaseDir"], "FILE\\");
                string path = "";
                var content_type = "";
                path = Path.Combine(BaseDir, filename);

                if (filename.Contains(".pdf"))
                {
                    content_type = "application/pdf";
                }

                return File(path, content_type, filename);

            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "DownloadTemplate Error: " + ex.Message;
            }
            return View();
        }


        public ActionResult DownloadBRSAttachment(string fileName)
        {
            try
            {
                string filename = fileName + ".pdf";
                string BaseDir = string.Concat(ConfigurationManager.AppSettings["FileServerBaseDir"], "FILE\\");
                string path = "";
                var content_type = "";
                path = Path.Combine(BaseDir, filename);

                if (filename.Contains(".pdf"))
                {
                    content_type = "application/pdf";
                }

                return File(path, content_type, filename);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "DownloadTemplate Error: " + ex.Message;
            }
            return View();
        }


        [HttpPost]
        public void UpdateBRS(BRSModel br)
        {
            try
            {
                BRSDto newBRS = new BRSDto
                {
                    BRSNo = br.BRSNo,
                    BRSApprovedDate = br.BRSApprovedDate,
                    //FilePath = br.FilePath,
                    //Filename = br.Filename,
                    Status = br.Status,
                    CreatedBy = br.CreatedBy,
                    DateCreated = DateTime.Now
                };
                _brsService.UpdateBRS(newBRS);

                PISDto UpdatePIS = new PISDto
                {
                    PISNo = br.PISNo,
                    AppName = br.PISModel.AppName,
                    Title = br.PISModel.Title,
                    AppDevNote = br.PISModel.AppDevNote,
                    AppDevComment = br.PISModel.AppDevComment,
                    ApprovedBy = br.PISModel.ApprovedBy,
                    DateApproved = br.PISModel.DateApproved,
                };
                _pISService.UpdateIsApproved(UpdatePIS);

                TempData["alertMessage"] = "Record has been successfully updated";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "System Error: " + ex.Message;
            }
        }


        public void Delete(int id)
        {
            try
            {
                Thread.Sleep(3000);
                _brsService.DeleteBRS(id);
                TempData["alertMessage"] = "Record has been successfully deleted";
            }
            catch (Exception ex)

PMS.Web/Controllers/MainController.cs
using AutoMapper;
using PMS.ApplicationService.DTOs;
using PMS.ApplicationService.ServiceContract;
using PMS.Common.Logger;
using PMS.Web.ActionFilters;
using PMS.Web.ViewModels;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

namespace PMS.Web.Controllers
{
    public class MainController : Controller
    {
        private readonly IPISService _pisService;
        private readonly IBRSService _brsService;
        private readonly IMapper _mapper;

        public MainController(IPISService pisService, IMapper mapper, IBRSService brsService)
        {
            if (pisService == null) throw new ArgumentNullException("PISService");
            if (brsService == null) throw new ArgumentNullException("BRSService");
            if (mapper == null) throw new ArgumentNullException("Mapper");
            _pisService = pisService;
            _brsService = brsService;
            _mapper = mapper;
        }

        public ActionResult Dashboard()
        {

            var countNew = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("new"));
            ViewBag.countNew = countNew.Count();

            var countCab = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("cab"));
            ViewBag.countCab = countCab.Count();

            var countPis = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("pis"));
            ViewBag.countPis = countPis.Count();

            var countAlladmin = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.getListStatus("all"));
            ViewBag.countAlladmin = countAlladmin.Count();

            var countAlluser = _mapper.Map<IEnumerable<PISDto>, IEnumerable<PISInformation>>(_pisService.GetAll());
            ViewBag.countAlluser = countAlluser.Count();

            var countBRS = _mapper.Map<IEnumerable<BRSDto>, IEnumerable<BRSModel>>(_brsService.GetAll());
            ViewBag.countBRS = countBRS.Count();


            // A array of authors  
            string[] divColor = { "warning", "success", "danger", "info", "primary"};
            // Create a Random object  
            Random rand = new Random();
            // Generate a random index less than the size of the array.  
            int index = rand.Next(divColor.Length);
            // Display the result.  
            string divPickColor = divColor[index].ToString();
            ViewBag.divPickColor = divPickColor;
            return View();
        }

    }
}

PMS.Web/Views/Main/Dashboard.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string pColor = "bg-" + ViewBag.divPickColor;
}
<style>
    /* CSS used here will be applied after bootstrap.css */
    .badge-notify {
        background: #029b46;
        position: relative;
        top: -25px;
        left: -10px;
    }
</style>
<!-- Breadcrumbs new-->
<ol class="breadcrumb wow fadeIn" data-wow-duration='2500ms' data-wow-delay='500ms'>
    <li class="breadcrumb-item active"><b>Overview</b></li>
</ol>


<h6>User Development two</h6>
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <a href="@Url.Action("Create", "PIS")" class="nounderline">
            <div class="card text-white @pColor o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                    </div>
                    <div class="mr-5"><b> Create PIS </b></div>
                </div>

            </div>
        </a>
    </div>

    @**@

    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>
                <div class="mr-5"><span class="cntTask">@ViewBag.countAlluser</span> My Tickets (Requestor)</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("List", "PIS")">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
</div>


<hr class="wow fadeIn" data-wow-duration='2500ms' data-wow-delay='1000ms' />

<h6>Admin</h6>
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>

                <div class="mr-5">
                    <span class="cntTask">@ViewBag.countNew</span>
                    <span class="badge badge-notify">New</span>
                    Submitted PIS
                </div>

            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("ProjectList", "PIS" , new { listname = "new" })">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>


    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>
                <div class="mr-5"><span class="cntTask">@ViewBag.countCab</span> For CAB Review</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("ProjectList", "PIS" , new { listname = "cab" })">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>


    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>
                <div class="mr-5"><span class="cntTask">@ViewBag.countPis</span> Approved PIS</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("ProjectList", "PIS" , new { listname = "pis" })">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>






    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>
                <div class="mr-5"><span class="cntTask">@ViewBag.countBRS</span> BRS List</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("List", "BRS")">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>



    <div class="col-xl-3 col-sm-6 mb-3 wow fadeInLeft" data-wow-duration='2500ms' data-wow-delay='500ms'>
        <div class="card text-white bg-dark o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list wow fadeInRight" data-wow-duration='2500ms' data-wow-delay='1000ms'></i>
                </div>
                <div class="mr-5">
                    <span class="cntTask">@ViewBag.countAlladmin</span>
                    <span class="badge badge-notify">New</span>
                    Project List
                </div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("ProjectList", "PIS" , new { listname = "all" })">
                <span class="float-left">View List</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>

</div>